### ISSUE TITLE
Distance to use and SeuratLSIClustering() argument "rmvariants"

### ISSUE THREAD

**Issue by alexwang1001** [chenweng1991/redeemR#8]
Hi Chen,

I don't have priors for the recommended weighted Jaccard distance for my tumor sample, so I tried LSI or plain Jaccard distance to build the tree. Based on the results below, which distance metrics would you recommend moving forward with?

Based on LSI distance:
![treeplot_with_VN](https://github.com/chenweng1991/redeemR/assets/49006271/d4b365cd-7fb6-4949-a540-4baebd8d7f75)

Based on Jaccard distance:
![treeplot_with_VN_jaccard](https://github.com/chenweng1991/redeemR/assets/49006271/1a292134-02d6-4f6a-a6d1-db1954e3f349)

Also, I saw that in the source code of the `SeuratLSIClustering` function, there is an argument `rmvariants=c("Variants310TC", "Variants3109TC", "Variants5764CT")`.
Could you please explain why we exclude these variants and if we should use the same list for other tissue types such as tumors?

Thank you,
Li

**Comment by chenweng1991** [comment]
Dear Li:
    Thank you for your question! I'm glad your experiment and data  preprocessing went well.  The mutation selection and appropriate weighting is a challenging part and may vary depending on different biological system. I would suggest play with both (and different mutations).  In principle, LSI will be contributed more by abundant variants.  The plain jaccard distance can be more even and can take into account the weight for different mutations (I use Jaccard more, but I feel both have values). We observed some mutations that are recurrently high across donors and therefore we down-wighted those mutations as "less informative", including Variants310TC, Variants3109TC, Variants5764CT by weighted jaccard distance.  As we cannot easily down-weight in LSI, we chose to remove them there. If the recurrent ones are similar, perhaps the prior I provided can be used to start with. 

Hope that helps. And I'm happy for more discussion
best regards
--Chen

**Comment by alexwang1001** [comment]
Thanks for the suggestion, Chen. I will take a look at the recurrent variants. I really appreciate it.
